### PR TITLE
fix spacing

### LINKED ISSUE #346: Reduce Gap Between Sections
image

### PR DESCRIPTION
**Pull request by menthy-wu**
image

### CODE REVIEW

File: src/components/Navigation.jsx [hunk 1]
```diff
@@ -53,28 +53,56 @@ const Navigation = () => {
...
+                            <p className="text-lg m-0 p-0">{tab.name}</p>
+                          </div>
+                        </Link>
+                      ))}
+                    </div>
+                  )
+              )}
+            </div>
+            <div className="w-full flex flex-col items-center">
+              {tabs[" "].map((tab, index) => (
```
Comment (shahdivyank) [inline src/components/Navigation.jsx:90]: try adding this directly into the config, like set the spacing in config

**Review by shahdivyank — APPROVED** [review]
