### PR TITLE
fixed calendar filters

### LINKED ISSUE #904: Fix Filtering
image
image

- Need to fix filtering, currently uses the old description formats, but it should use the new formats
- First hastag is the filterable group, and the second hashtag is the assignee

### PR DESCRIPTION
**Pull request by seanquiambao**
before: image

after:
image

### CODE REVIEW

File: src/components/dynamic/admin/services/calendar/Toolbar.jsx [hunk 1]
```diff
@@ -24,8 +24,12 @@ const CustomToolbar = ({
       setEvents(
         events.map((event) => {
           if (
-            event.description.split("\n")[1].split(": ")[1].toLowerCase() ===
-            value
+            event.description
+              .split("\n")[0]
+              .split("#")
+              .map((item) => item.trim())
+              .filter((item) => item !== "")[0]
```
Comment (shahdivyank) [inline src/components/dynamic/admin/services/calendar/Toolbar.jsx:30]: u can combine the trim and filters u can just do item.trim() !== ""

**Review by shahdivyank — APPROVED** [review]
