### PR TITLE
fixed made

### LINKED ISSUE #805: Move Protected Page to Layout Level
- would not require to run protected page on every page
- need to bypass index page 
- need to ensure rules stay intact

### PR DESCRIPTION
**Pull request by Lackline**

### CODE REVIEW

File: src/data/ProtectedRoutes.js [hunk 1]
```diff
@@ -0,0 +1,177 @@
+export const ROUTES = {
+  "/": {
+    bypass: true,
```
Comment (shahdivyank) [inline src/data/ProtectedRoutes.js:3]: need a title here

File: src/data/ProtectedRoutes.js [hunk 2]
```diff
@@ -0,0 +1,177 @@
...
+  },
+  "/_not-found": {
```
Comment (shahdivyank) [inline src/data/ProtectedRoutes.js:6]: need title

File: src/data/ProtectedRoutes.js [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+    bypass: true,
+  },
+  "/_error": {
```
Comment (shahdivyank) [inline src/data/ProtectedRoutes.js:10]: title

**Review by shahdivyank — APPROVED** [review]
