### PR TITLE
Fixed Issue acm-ucr#1358: Simplify Words

### LINKED ISSUE #1358: Simplify Words
image

- Remove secondary and keep just high school in both less than HS and HS
- Remove University from Undergrad and Grad
-

### PR DESCRIPTION
**Pull request by FireHeart003**
- Got rid of the term secondary and university as they were redundant
- This resolved the issue, PR ready for review

### CODE REVIEW

File: src/data/form/Information.js [hunk 1]
```diff
@@ -1,8 +1,8 @@
 export const SHIRTS = ["XS", "S", "M", "L", "XL", "XXL"];
 
 export const GRADES = [
-  "Less than Secondary / High School",
-  "Secondary / High School",
+  "Less than High School",
+  "High School",
   "Undergraduate University",
```
Comment (shahdivyank) [inline src/data/form/Information.js]: Remove university

File: src/data/form/Information.js [hunk 2]
```diff
@@ -1,8 +1,8 @@
...
   "Graduate University (Masters, Doctoral, etc)",
```
Comment (shahdivyank) [inline src/data/form/Information.js]: Remove university

File: src/data/form/Information.js (hunk 1 above)
Comment (shahdivyank) [inline src/data/form/Information.js]:
```suggestion
  "Undergraduate",
```

File: src/data/form/Information.js (hunk 2 above)
Comment (shahdivyank) [inline src/data/form/Information.js]:
```suggestion
  "Graduate (Masters, Doctoral, etc)",
```

**Review by shahdivyank — APPROVED** [review]
