### PR TITLE
Fixed Empty Message

### LINKED ISSUE #1545: Fix Empty Message
image

- When on the judges view, it should say no judges available instead of teams

### PR DESCRIPTION
**Pull request by sunbrandon**
Screenshot 2024-07-13 at 8 32 43 PM
Changed the empty text message on judges view from "No teams available" to "No judges available"

### CODE REVIEW

File: src/components/admin/services/judging/Judging.jsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ const Judging = () => {
       <Title title={view ? "Judges" : "Teams"} />
       {filters === null || filters.length === 0 ? (
         <div className="flex-grow flex items-center justify-center">
-          No teams available
+          {view ? "No judges available" : "No teams available"}
```
Comment (shahdivyank) [inline src/components/admin/services/judging/Judging.jsx]:
```suggestion
          {view ? "No Judges Available" : "No Teams Available"}
```

**Review by shahdivyank — APPROVED** [review]
