### PR TITLE
Fix Form Bug

### LINKED ISSUE #749: Fix Form Bug
image

- Reproduce: Do not meet all the requirements, then press submit, then fix the error and then submit again
- You are not able to resubmit, forcing you to refresh

### PR DESCRIPTION
**Pull request by vwong031**
- Closes #749

### CODE REVIEW

File: src/components/dynamic/forms/Form.jsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ const Form = ({ object, setObject, header, fields, onSubmit }) => {
       )
     ) {
       toast("❌ Please complete all required fields!");
+      setLoading(false); // Reset loading state
```
Comment (shahdivyank) [inline src/components/dynamic/forms/Form.jsx]: remove the comments

**Review by shahdivyank — APPROVED** [review]

**Review by menthy-wu — APPROVED** [review]

**Review by rfairooz — APPROVED** [review]
