### PR TITLE
Fixed Change Settings Logging #1150 and Completed Reduce Spacing #1183

### LINKED ISSUE #1150: Change Settings Logging
- Currently the settings page uses a custom `message` state to log errors/success
- Change it to use our custom toaster

### LINKED ISSUE #1183: Reduce Spacing
image

- Reduce spacing between resources and MLH code of conduct

### PR DESCRIPTION
**Pull request by ZaraFairooz**
Screenshot 2024-07-10 at 11 09 05 PM

Screenshot 2024-07-09 at 2 23 44 AM

### CODE REVIEW

File: src/components/admin/services/settings/Settings.jsx [hunk 1]
```diff
@@ -2,16 +2,17 @@
 import Title from "@/components/admin/Title";
 import { api } from "@/utils/api";
 import Button from "../../Button";
-import { useState } from "react";
+import { showToast } from "@/utils/toaster";
```
Comment (shahdivyank) [inline src/components/admin/services/settings/Settings.jsx]: should be called toaster (this is how its called everywhere else)

File: src/components/form/form/Questions.jsx [hunk 2]
```diff
@@ -185,16 +185,17 @@ const Questions = ({
...
-
-      <Link
-        href="https://static.mlh.io/docs/mlh-code-of-conduct.pdf"
-        target="_blank"
-        className="no-underline flex items-center text-hackathon-green-300 hover:text-opacity-65"
-      >
-        MLH Code of Conduct
-        <FaLink className="mx-2" />
-      </Link>
+      <p>
```
Comment (shahdivyank) [inline src/components/form/form/Questions.jsx]: p tags shouldn't have p tags integrated in them

**Review by shahdivyank — APPROVED** [review]
