### PR TITLE
Fixed overflow issue with navbar tabs

### LINKED ISSUE #1252: Fix Navigation Scroll
image

- Navigation should be scrollable, instead of being fixed and going off the navbar

### PR DESCRIPTION
**Pull request by DannielK**
image
image

Navbar is scrollable now, fixing overflowed tabs

### CODE REVIEW

File: src/components/Navigation.jsx [hunk 1]
```diff
@@ -32,11 +32,11 @@ const Navigation = () => {
         </div>
       </div>
       <div
-        className={`z-10 lg:flex lg:w-[12%] ${
+        className={`overflow-auto z-10 lg:flex lg:w-[12%] ${
```
Comment (shahdivyank) [inline src/components/Navigation.jsx]: make it explicit and do scroll

File: src/components/Navigation.jsx [hunk 2]
```diff
@@ -32,11 +32,11 @@ const Navigation = () => {
...
           expand ? "left-0 h-screen w-1/2 fixed pt-5" : `hidden`
         }`}
       >
-        <div className="bg-hackathon-blue-200 h-full flex flex-col justify-between items-center w-full">
+        <div className="overflow-auto bg-hackathon-blue-200 h-full flex flex-col justify-between items-center w-full">
```
Comment (shahdivyank) [inline src/components/Navigation.jsx]: make it explicit and scroll

**Review by shahdivyank — APPROVED** [review]
