### PR TITLE
fixed resize issue

### LINKED ISSUE #190: BUG: Prevent Autoresize
image

### PR DESCRIPTION
**Pull request by AnjalineSingh**

### CODE REVIEW

**Comment by AnjalineSingh** [comment]
Screen Shot 2023-09-05 at 7 38 31 PM

**Comment by AnjalineSingh** [comment]
Screen Shot 2023-09-05 at 7 45 50 PM

File: src/components/Forms/Textarea.jsx [hunk 1]
```diff
@@ -37,6 +37,7 @@ const Textarea = ({
         name={name}
         placeholder={placeholder}
         value={value}
+        style={{ resize: "none", height: "50px" }}
```
Comment (shahdivyank) [inline src/components/Forms/Textarea.jsx]: this can be done via tailwind, make the height based on characters if possible, but everything should be in tailwind

**Comment by shahdivyank** [comment]
Attach issue

**Comment by AnjalineSingh** [comment]
the resize is in tailwind but making the height based off the user's characters is not possible to be done via tailwind.

**Comment by shahdivyank** [comment]
image
Try this and leave it at maybe 4-5?

**Comment by AnjalineSingh** [comment]
i used h-auto + rows = 5 and it did not set the text to the amount of rows. but it doesn't allow the user to expand the box like before either


https://github.com/acm-ucr/hackathon-website/assets/117554632/0dc12162-4783-4e8c-a87b-735e43800816

**Comment by shahdivyank** [comment]
> i used h-auto + rows = 5 and it did not set the text to the amount of rows. but it doesn't allow the user to expand the box like before either
> 
>  Screen.Recording.2023-09-12.at.10.30.08.PM.mov

You have to apply it to the tag itself, not as a classname

**Comment by AnjalineSingh** [comment]
> > i used h-auto + rows = 5 and it did not set the text to the amount of rows. but it doesn't allow the user to expand the box like before either
> > Screen.Recording.2023-09-12.at.10.30.08.PM.mov
> 
> You have to apply it to the tag itself, not as a classname

oh my bad! I’ll fix it tonight

**Review by menthy-wu — APPROVED** [review]

**Review by shahdivyank — APPROVED** [review]
