### PR TITLE
attatchement and fix checkin

### LINKED ISSUE #326: Change Default
image

- When the page is loaded, accepted should be turned on by default

### LINKED ISSUE #327: Add Attachment Option
image

- Need to be able to send images/pdfs to these users if needed
- Create an Upload like feature that can take care of this

### LINKED ISSUE #328: Make Capitalization the Same
image

- Subject needs to be lowercased

### LINKED ISSUE #359: Rename to CheckIn Page
image

### LINKED ISSUE #361: BUG: Filtering on Event
image

- Filter doesn't reset, need to keep track of lost items as well, can employ the hidden attribute technique used in the tables

### LINKED ISSUE #362: No Info Should be Centered
image

### LINKED ISSUE #363: Make Input Square
image

### LINKED ISSUE #364: Fix Arrow Animation
image

- Arrow should change direction to reflect open or closed

### LINKED ISSUE #365: Empty Output
image

- When clicking checkin without scanning a QR code it shows a white box, when it should still show no info

### LINKED ISSUE #366: Add Scroll
image

- With many events, the dropdown will continue to go down, need to stop after a few events and then offer a scrolling option

### PR DESCRIPTION
**Pull request by menthy-wu**
image

### CODE REVIEW

**Comment by menthy-wu** [comment]
I forget to switch branch sorry

File: src/components/Admin/DropDown.jsx [hunk 1]
```diff
@@ -1,30 +1,30 @@
...
 };
-const Menu = ({ children, className, setOptions, options }) => {
+const Menu = ({ children, className, setOptions, reset }) => {
   const [value, setValue] = useState("");
   return (
     <div className={className}>
       <input
         autoFocus
-        className="mx-3 my-2 w-fit ring-0 outline-none"
+        className="mx-3 my-2 w-11/12 focus:ring-0 !outline-0, border-gray-300 border-[1px] text-sm px-2 py-1"
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: do u need the focus and the outline? also pretty sure u don't need the !

File: src/components/Admin/DropDown.jsx [hunk 2]
```diff
@@ -34,25 +34,39 @@ const Menu = ({ children, className, setOptions, options }) => {
     </div>
   );
 };
-const DropDown = ({ options, setOption, option, setOptions }) => {
+const DropDown = ({ options, setOption, option, setOptions, reset }) => {
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: can you order this correctly

File: src/components/Admin/DropDown.jsx [hunk 3]
```diff
@@ -34,25 +34,39 @@ const Menu = ({ children, className, setOptions, options }) => {
...
+  const [show, setShow] = useState(false);
   return (
-    <Dropdown className="w-full m-0 bg-white rounded-3xl">
-      <Dropdown.Toggle as={Toggle}>{option}</Dropdown.Toggle>
+    <Dropdown
+      onToggle={() => {
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: implicit return

File: src/components/Admin/DropDown.jsx [hunk 4]
```diff
@@ -34,25 +34,39 @@ const Menu = ({ children, className, setOptions, options }) => {
...
-          <Dropdown.Item
-            className=" hover:!bg-hackathon-green-200 bg-transparent overflow-hidden px-3 py-1 last:rounded-b-xl"
-            key={index}
-            onClick={() => setOption(currOoption)}
-          >
-            {currOoption}
-          </Dropdown.Item>
-        ))}
+        {options.length > 0 ? (
+          options.map((currOoption, index) => (
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: spelling

File: src/components/Admin/Messenger.jsx [hunk 5]
```diff
@@ -7,90 +7,76 @@ import Input from "./Input";
...
+    if (email.body === "") {
       toast("❌ Please add a body!");
       return;
     }
-    const emails = filteredParticipants.map((user) => user.email);
-    console.log({
-      sendto: emails,
-      subject: subjectText,
-      body: messageBody,
+    const emails = user.filter((user) => {
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx]: don't need this, assume that u will get an emails array directly, we will need to make a backend call anyways otherwise we have to grab all the user information which is not needed

File: src/components/Admin/Messenger.jsx [hunk 6]
```diff
@@ -7,90 +7,76 @@ import Input from "./Input";
...
+      let select = false;
+      Object.entries(filters).forEach(([filter, selected]) => {
+        if (selected && (user.status == filter || user.role == filter)) {
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx]: why do we need status?

File: src/components/Admin/Messenger.jsx [hunk 7]
```diff
@@ -7,90 +7,76 @@ import Input from "./Input";
...
+          select = true;
+        }
+      });
+      if (select) return user.email;
+      return false;
     });
     toast(`✅ Email sent successfully!`);
+    setEmail({ ...email, sendto: emails });
+    console.log(email);
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx:31]: remove console logs

File: src/components/Admin/Messenger.jsx [hunk 8]
```diff
@@ -7,90 +7,76 @@ import Input from "./Input";
...
           <p className="text-lg font-extrabold mb-1">body:</p>
-          <Textarea value={messageBody} setValue={setMessageBody} />
-          <div className="flex w-full justify-end mt-3">
+          <Textarea
+            setValue={(value) => setEmail({ ...email, body: value })}
+            value={email.body}
+          />
+          <div className="flex w-full justify-between mt-3 items-end">
+            <Upload
+              setObjects={(files) => {
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx]: implicit return

File: src/components/Admin/Upload.jsx [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+
+  const handleInput = (e) => {
+    setUploading(true);
+    if (files.length + e.target.files.length > 5) {
+      toast("❌ Exceeds 5 files!");
+      return;
+    }
+    const fileList = [];
+    Object.entries(e.target.files).forEach(([ind, file]) => {
+      if (file.size > 1048576) {
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx]: can you make this a constant at the top of the code like 

const 1MB = 1048576

File: src/components/Admin/Upload.jsx [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+        toast("❌ File too big, exceeds 1MB!");
+      } else fileList.push(file);
+    });
+    setFiles([...files, ...fileList]);
+    setObjects([...files, ...fileList]);
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx]: why do you push both, also Objects is an object not an array

File: src/components/Admin/Upload.jsx [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+      <div className="flex flex-col items-start">
+        {uploading && <p>uploading...</p>}
+        <Row className="p-0 m-0">
+          {files.map((file, index) => (
+            <Col
+              key={index}
+              className="flex items-center bg-hackathon-gray px-2 py-1 mb-1 mr-1 !max-w-fit p-0"
+            >
+              <p className="text-sm m-0 whitespace-nowrap text-gray-500 font-semibold ">
+                {file.name} ({Math.round(file.size / 10.24) / 100}KB)
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx]: conver to a function and then call that function

File: src/components/Admin/Upload.jsx [hunk 12]
```diff
@@ -0,0 +1,72 @@
...
+              </p>
+              <FaTimes
+                className="text-hackathon-darkgray text-sm ml-2 hover:cursor-pointer hover:text-red-600"
+                onClick={() => {
+                  setFiles(files.filter((file, idx) => index != idx));
+                  setObjects(files.filter((file, idx) => index != idx));
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx]: shouldn't need 2 instances

File: src/components/Admin/CheckIn.jsx [hunk 13]
```diff
@@ -21,14 +21,15 @@ const CheckIn = () => {
...
-      <Title title="Mentors" />
+      <Title title="Check In" />
       <Row className="p-0 m-0">
         <Col xs={12} md={6} className="p-3 m-0 flex flex-col justify-around">
           <DropDown
             option={event}
             setOption={setEvent}
             options={events}
             setOptions={setEvents}
+            reset={mockEvents}
```
Comment (shahdivyank) [inline src/components/Admin/CheckIn.jsx]: read the issue.... 😭

File: src/components/Admin/Messenger.jsx [hunk 14]
```diff
@@ -7,90 +7,76 @@ import Input from "./Input";
...
-  const [messageBody, setMessageBody] = useState("");
-  const [filters, setFilters] = useState({
-    accepted: false,
-    rejected: false,
-    pending: false,
-    volunteers: false,
-    mentors: false,
-    judges: false,
+  const [email, setEmail] = useState({
+    sendto: [],
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx:15]: call this emails

File: src/components/Admin/Messenger.jsx [hunk 15]
```diff
@@ -7,90 +7,76 @@ import Input from "./Input";
...
+    subject: "",
+    body: "",
+    files: [],
   });
-  const [filteredParticipants, setfilteredParticipants] = useState(ADDRESSEES);
+  const [filters, setFilters] = useState(messengerFilters);
+  const [user, setUser] = useState(userList);
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx]: don't need a user state, you will be getting ur data in an array, we will do processing in backend for participants -> participants.emails

File: src/components/Admin/Messenger.jsx [hunk 16]
```diff
@@ -7,90 +7,76 @@ import Input from "./Input";
...
-            objects={ADDRESSEES}
+            setObjects={setUser}
+            objects={user}
+            input=""
           />
         </div>
         <Input
-          setValue={setSubjectText}
-          value={subjectText}
+          setValue={(value) => setEmail({ ...email, subject: value })}
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx]: this should become a generic function, checkout out the other input tags do it

File: src/components/Admin/Messenger.jsx [hunk 17]
```diff
@@ -7,90 +7,76 @@ import Input from "./Input";
...
-          label="Subject:"
+          label="subject:"
           placeholder="subject"
         />
         <div className="w-full h-full bg-white rounded-2xl my-2 flex flex-col p-4 pt-2">
           <p className="text-lg font-extrabold mb-1">body:</p>
-          <Textarea value={messageBody} setValue={setMessageBody} />
-          <div className="flex w-full justify-end mt-3">
+          <Textarea
+            setValue={(value) => setEmail({ ...email, body: value })}
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx]: should be generic

**Review by shahdivyank — CHANGES_REQUESTED** [review]

File: src/components/Admin/CheckIn.jsx [hunk 18]
```diff
@@ -13,15 +13,15 @@ const CheckIn = () => {
   const setResult = (result) => {
     setInfo(checkInUser[result]);
   };
-  const [event, setEvent] = useState(mockEvents[0]);
+  const [event, setEvent] = useState(mockEvents[0].name);
   const [events, setEvents] = useState(mockEvents);
   const [info, setInfo] = useState(null);
   const onClick = () => {
-    setInfo({ ...info, [event]: true });
+    info && setInfo({ ...info, [event]: true });
```
Comment (shahdivyank) [inline src/components/Admin/CheckIn.jsx]: why do u need the info &&

File: src/components/Admin/DropDown.jsx [hunk 19]
```diff
@@ -18,14 +18,15 @@ const Menu = ({ children, className, setOptions, options }) => {
     <div className={className}>
       <input
         autoFocus
-        className="mx-3 my-2 w-fit ring-0 outline-none"
+        className="mx-3 my-2 w-11/12 ring-0 !outline-0 border-gray-300 border-[1px] text-sm px-2 py-1"
         placeholder="Type to filter..."
         onChange={(e) => {
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: put this in a function

File: src/components/Admin/DropDown.jsx [hunk 20]
```diff
@@ -34,25 +35,40 @@ const Menu = ({ children, className, setOptions, options }) => {
...
-        {options.map((currOoption, index) => (
-          <Dropdown.Item
-            className=" hover:!bg-hackathon-green-200 bg-transparent overflow-hidden px-3 py-1 last:rounded-b-xl"
-            key={index}
-            onClick={() => setOption(currOoption)}
-          >
-            {currOoption}
-          </Dropdown.Item>
-        ))}
+        {options.filter((opt, index) => !opt.hidden).length > 0 ? (
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: remove the index param if u don't need it

File: src/components/Admin/DropDown.jsx [hunk 21]
```diff
@@ -34,25 +35,40 @@ const Menu = ({ children, className, setOptions, options }) => {
...
+          options.map(
+            (currOption, index) =>
+              !currOption.hidden && (
+                <Dropdown.Item
+                  className=" hover:!bg-hackathon-green-200 bg-transparent overflow-hidden px-3 py-1 last:rounded-b-xl"
+                  key={index}
+                  onClick={() => setOption(currOption.name)}
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: call currOption, just current

File: src/components/Admin/Input.jsx [hunk 22]
```diff
@@ -1,26 +1,26 @@
...
+      <p className="text-lg font-extrabold mr-2 my-0">{label}:</p>
       <div className="flex items-center my-1 bg-hackathon-gray rounded-md w-full">
         <input
-          value={value}
+          value={object[label]}
           maxLength={maxLength}
           placeholder={placeholder}
           type="text"
           className="outline-none w-full font-poppins text-base py-1 bg-transparent px-2"
           onChange={(e) => {
```
Comment (shahdivyank) [inline src/components/Admin/Input.jsx]: make this a function, otherwise u have to copy paste the setObject thing multiple times, the entire point was to prevent the copy paste

File: src/components/Admin/Messenger.jsx [hunk 23]
```diff
@@ -7,90 +7,60 @@ import Input from "./Input";
...
+      <div className="flex flex-col pb-3 pt-4 h-full items-stretch justify-between">
         <Title title="Messenger" />
         <div className="flex items-center my-1">
           <p className="text-lg font-extrabold mr-5 my-0">to:</p>
           <Filters
             filters={filters}
             setFilters={setFilters}
-            setObjects={setfilteredParticipants}
-            objects={ADDRESSEES}
+            setObjects={() => {}}
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx:42]: is it possible to not even mention these params, and instead have them as defaults in the function definition

File: src/components/Admin/DropDown.jsx [hunk 24]
```diff
@@ -1,58 +1,76 @@
...
     </button>
   );
 };
 const Menu = ({ children, className, setOptions, options }) => {
+  const handleInput = (e) => {
+    setValue(e.target.value);
+    setOptions(
+      options.map((option) => ({
+        ...option,
+        hidden: !option.name.toLowerCase().includes(e.target.value),
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: e.target.value also needs to be lowercased and trimmed

File: src/components/Admin/DropDown.jsx [hunk 25]
```diff
@@ -1,58 +1,76 @@
...
+      }))
+    );
+  };
   const [value, setValue] = useState("");
   return (
     <div className={className}>
       <input
         autoFocus
-        className="mx-3 my-2 w-fit ring-0 outline-none"
+        className="mx-3 my-2 w-11/12 ring-0 !outline-0 border-gray-300 border-[1px] text-sm px-2 py-1"
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: try outline-none that should solve the outline-0 thing, you shouldn't need the !

File: src/components/Admin/DropDown.jsx [hunk 26]
```diff
@@ -1,58 +1,76 @@
...
   return (
-    <Dropdown className="w-full m-0 bg-white rounded-3xl">
-      <Dropdown.Toggle as={Toggle}>{option}</Dropdown.Toggle>
+    <Dropdown
+      onToggle={() => setShow(!show)}
+      show={show}
+      autoClose={true}
+      className="w-full m-0 bg-white rounded-3xl"
+    >
+      <Dropdown.Toggle show={show} as={Toggle}>
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: is it possible u can pass the option in directly so u dont have to do the children thing

Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: Try this, not sure if it will work
```suggestion
      <Dropdown.Toggle show={show} as={(props) => <Toggle {...props} option = {option}/>}>
```

File: src/components/Admin/DropDown.jsx [hunk 27]
```diff
@@ -1,58 +1,76 @@
...
+        {option}
+      </Dropdown.Toggle>
       <Dropdown.Menu
         as={Menu}
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx:67]: try the same thing here so u dont need the children

File: src/components/Admin/DropDown.jsx [hunk 28]
```diff
@@ -1,58 +1,76 @@
...
-            className=" hover:!bg-hackathon-green-200 bg-transparent overflow-hidden px-3 py-1 last:rounded-b-xl"
-            key={index}
-            onClick={() => setOption(currOoption)}
-          >
-            {currOoption}
-          </Dropdown.Item>
-        ))}
+        {options.filter((opt) => !opt.hidden).length > 0 ? (
+          options.map(
+            (current, index) =>
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: oh lol, hehe ma bad, but this should be option not current. I thought it was referring to a useState

Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]:
```suggestion
            (option, index) =>
```

File: src/components/Admin/DropDown.jsx [hunk 29]
```diff
@@ -1,58 +1,76 @@
...
+              !current.hidden && (
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]:
```suggestion
              !option.hidden && (
```

File: src/components/Admin/DropDown.jsx [hunk 30]
```diff
@@ -1,58 +1,76 @@
...
+                <Dropdown.Item
+                  className=" hover:!bg-hackathon-green-200 bg-transparent overflow-hidden px-3 py-1 last:rounded-b-xl"
+                  key={index}
+                  onClick={() => setOption(current.name)}
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]:
```suggestion
                  onClick={() => setOption(option.name)}
```

File: src/components/Admin/DropDown.jsx [hunk 31]
```diff
@@ -1,58 +1,76 @@
...
+                >
+                  {current.name}
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]:
```suggestion
                  {option.name}
```

File: src/components/Admin/DropDown.jsx [hunk 32]
```diff
@@ -1,58 +1,76 @@
...
+                </Dropdown.Item>
+              )
+          )
+        ) : (
+          <p className="px-3 text-gray-400">no info</p>
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: should be no options, no items or something like that instead of info

File: src/components/Admin/Input.jsx [hunk 33]
```diff
@@ -1,26 +1,27 @@
...
+    setObject({ ...object, [label]: e.target.value });
+  };
   return (
     <div className="flex items-center">
-      <p className="text-lg font-extrabold mr-2 my-0">{label}</p>
+      <p className="text-lg font-extrabold mr-2 my-0">{label}:</p>
       <div className="flex items-center my-1 bg-hackathon-gray rounded-md w-full">
         <input
-          value={value}
+          value={object[label]}
```
Comment (shahdivyank) [inline src/components/Admin/Input.jsx:13]: does this work everywhere where the input tag is called?

File: src/components/Admin/Input.jsx [hunk 34]
```diff
@@ -1,26 +1,27 @@
...
-            setValue(e.target.value);
-          }}
+          onChange={handleInput}
         />
         {clear && (
           <MdCancel
             className="hover:cursor-pointer text-xl text-hackathon-darkgray mr-2"
             onClick={() => {
-              setValue("");
+              setObject({ ...object, [label]: "" });
```
Comment (shahdivyank) [inline src/components/Admin/Input.jsx]: make it inline, u dont need the curly braces

File: src/components/Admin/Messenger.jsx [hunk 35]
```diff
@@ -7,90 +7,60 @@ import Input from "./Input";
...
-  const [subjectText, setSubjectText] = useState("");
-  const [messageBody, setMessageBody] = useState("");
-  const [filters, setFilters] = useState({
-    accepted: false,
-    rejected: false,
-    pending: false,
-    volunteers: false,
-    mentors: false,
-    judges: false,
+  const [emails, setEmails] = useState({
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx]: should be email, setEmail, there is only one email we are doing at a time

File: src/components/Admin/Messenger.jsx [hunk 36]
```diff
@@ -7,90 +7,60 @@ import Input from "./Input";
...
           <p className="text-lg font-extrabold mb-1">body:</p>
-          <Textarea value={messageBody} setValue={setMessageBody} />
-          <div className="flex w-full justify-end mt-3">
+          <Textarea setObject={setEmails} object={emails} label="body" />
+          <div className="flex w-full justify-between mt-3 items-end">
+            <Upload
+              setObjects={setEmails}
+              objects={emails}
+              sizeLimit="1 MB"
+              typeLimit=""
```
Comment (shahdivyank) [inline src/components/Admin/Messenger.jsx]: if there's no type limit then remove it

Comment (shahdivyank) [reply src/components/Admin/Messenger.jsx]: but there should be type limits, only pdf and image types

File: src/components/Admin/Textarea.jsx [hunk 37]
```diff
@@ -1,12 +1,12 @@
 import React from "react";
 
-const Textarea = ({ value, setValue }) => {
+const Textarea = ({ object, setObject, label }) => {
   return (
     <textarea
       className="w-full h-full border-2 rounded-md p-2 resize-none outline-none"
-      value={value}
+      value={object[label]}
```
Comment (shahdivyank) [inline src/components/Admin/Textarea.jsx:7]: does this work everywhere this component is called?

File: src/data/mock/messengerUsers.js [hunk 38]
```diff
@@ -0,0 +1,50 @@
+export const userList = [
```
Comment (shahdivyank) [inline src/data/mock/messengerUsers.js]: this should only be an array of emails

File: src/components/Admin/CheckIn.jsx [hunk 39]
```diff
@@ -13,15 +13,13 @@ const CheckIn = () => {
   const setResult = (result) => {
     setInfo(checkInUser[result]);
   };
-  const [event, setEvent] = useState(mockEvents[0]);
+  const [event, setEvent] = useState(mockEvents[0].name);
```
Comment (shahdivyank) [inline src/components/Admin/CheckIn.jsx]: there should be no default event, it should just be like something generic like "No Event Selected"

File: src/components/Admin/CheckIn.jsx [hunk 40]
```diff
@@ -13,15 +13,13 @@ const CheckIn = () => {
...
   const [events, setEvents] = useState(mockEvents);
   const [info, setInfo] = useState(null);
-  const onClick = () => {
-    setInfo({ ...info, [event]: true });
-  };
+  const onClick = () => etInfo({ ...info, [event]: true });
```
Comment (shahdivyank) [inline src/components/Admin/CheckIn.jsx]: u have a typo, did u test ur code?

File: src/components/Admin/DropDown.jsx [hunk 41]
```diff
@@ -1,59 +1,76 @@
...
-          );
-        }}
+        onChange={handleInput}
         value={value}
       />
-      {children}
+      {options.filter((opt) => !opt.hidden).length > 0 ? (
+        options.map(
+          (option, index) =>
+            !option.hidden && (
```
Comment (shahdivyank) [inline src/components/Admin/DropDown.jsx]: filter the array first and then map through it, it will remove the need for this check

File: src/components/Admin/Upload.jsx [hunk 42]
```diff
@@ -0,0 +1,83 @@
+import React, { useState } from "react";
+import { RiAttachment2 } from "react-icons/ri";
+import { FaTimes } from "react-icons/fa";
+import { toast } from "react-hot-toast";
+import { Row, Col } from "react-bootstrap";
+
+const bytes = {
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx]: extract this so the upload from forms can also use it

File: src/components/Admin/Upload.jsx [hunk 43]
```diff
@@ -0,0 +1,83 @@
...
+  MB: 1048576,
+  GB: 1073741824,
+};
+const getSize = (maxSize) => bytes[maxSize[1]] * maxSize[0];
+const getType = (types) => "." + types.join(",.");
+const displayFile = (file) =>
+  `${file.name} (${Math.round(file.size / 10.24) / 100}KB)`;
+const Upload = ({ text, setObjects, objects, size, types }) => {
+  const [uploading, setUploading] = useState(false);
+  const fileList = [];
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx]: - dont declare outside a function
- why do we need a copy?

File: src/components/Admin/Upload.jsx [hunk 44]
```diff
@@ -0,0 +1,86 @@
...
+import { FaTimes } from "react-icons/fa";
+import { toast } from "react-hot-toast";
+import { Row, Col } from "react-bootstrap";
+
+import { bytes } from "@/data/bytes";
+const getSize = (maxSize) => bytes[maxSize[1]] * maxSize[0];
+const getType = (types) => "." + types.join(",.");
+const displayFile = (file) =>
+  `${file.name} (${Math.round(file.size / 10.24) / 100}KB)`;
+const Upload = ({ text, setObjects, objects, size, types }) => {
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx:13]:
```suggestion

const Upload = ({ text, setObjects, objects, size, types }) => {
```

File: src/components/Admin/Upload.jsx [hunk 45]
```diff
@@ -0,0 +1,87 @@
...
+    setUploading(false);
+  };
+
+  return (
+    <div className="mt-3">
+      <p className="mb-0">{text}</p>
+      <div className="flex flex-col items-start">
+        {uploading && <p>uploading...</p>}
+        <Row className="p-0 m-0">
+          {objects?.files.map((file, index) => (
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx:46]: shouldn't need this

File: src/components/Admin/Upload.jsx [hunk 46]
```diff
@@ -0,0 +1,87 @@
...
+            >
+              <p className="text-sm m-0 whitespace-nowrap text-gray-500 font-semibold ">
+                {displayFile(file)}
+              </p>
+              <FaTimes
+                className="text-hackathon-darkgray text-sm ml-2 hover:cursor-pointer hover:text-red-600"
+                onClick={() => {
+                  setObjects({
+                    ...objects,
+                    files: objects.files.filter((file, idx) => index != idx),
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx]:
```suggestion
                    files: objects.files.filter((file, idx) => index !== idx),
```

File: src/components/Admin/Upload.jsx [hunk 47]
```diff
@@ -0,0 +1,87 @@
...
+      return;
+    }
+
+    setObjects({
+      ...objects,
+      files: [
+        ...objects.files,
+        ...Object.values(e.target.files).filter((file) => {
+          if (file.size > getSize(size)) {
+            toast(`❌ ${file.name} exceeds  ${size[0]} ${size[1]}`);
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx]:
```suggestion
            toast(`❌ ${file.name} exceeds ${size[0]} ${size[1]}`);
```

File: src/components/Admin/Upload.jsx [hunk 48]
```diff
@@ -0,0 +1,87 @@
...
+          ))}
+        </Row>
+        <label
+          htmlFor="dropzone-file"
+          className="flex items-center justify-center w-git border-2 border-gray-300 rounded cursor-pointer bg-gray-50 hover:bg-gray-100 px-2 py-1 m-0"
+        >
+          <RiAttachment2 className="text-xl text-gray-500 mr-1" />
+          <p className="text-sm text-gray-500 font-semibold m-0">attach</p>
+          <input
+            id="dropzone-file"
```
Comment (shahdivyank) [inline src/components/Admin/Upload.jsx:73]: what's the id for?

**Review by shahdivyank — APPROVED** [review]
