### PR TITLE
fix team error

### LINKED ISSUE #759: Create New Team Error
image

### PR DESCRIPTION
**Pull request by menthy-wu**

### CODE REVIEW

File: src/app/api/members/route.js [hunk 1]
```diff
@@ -15,7 +15,9 @@ export async function DELETE() {
   const res = NextResponse;
   // TODO: WHAT AUTHENTICATION IS NEEDED HERE?
```
Comment (shahdivyank) [inline src/app/api/members/route.js]: remove the todo comment

File: src/app/api/members/route.js [hunk 2]
```diff
@@ -15,7 +15,9 @@ export async function DELETE() {
...
   const { auth, message, user } = await authenticate({
-    admins: 1,
+    participants: -1,
```
Comment (shahdivyank) [inline src/app/api/members/route.js]: should work if u use an array

**Review by shahdivyank — APPROVED** [review]

**Review by rfairooz — APPROVED** [review]
