### PR TITLE
fix hover

### LINKED ISSUE #384: Remove Hover
image

- Should not be able to hover on it

### LINKED ISSUE #385: Remove Status Hover
image

- Should not be able to hover on status

### LINKED ISSUE #387: Remove Status Hover
image

### LINKED ISSUE #388: Remove Status Hover
image

### LINKED ISSUE #391: Remove Hover Status
image

### LINKED ISSUE #393: Remove Status Hover
image

### PR DESCRIPTION
**Pull request by menthy-wu**

### CODE REVIEW

File: src/components/Admin/Table.jsx [hunk 1]
```diff
@@ -107,7 +107,11 @@ const Table = ({ headers, setHeaders, empty, setObjects, objects }) => {
                                 : object[header.text]
                             }
                             color={colors[object[header.text]]}
-                            onClick={() => header.onClick(object)}
+                            onClick={
```
Comment (shahdivyank) [inline src/components/Admin/Table.jsx]: can this be done at a tag level instead

**Review by shahdivyank — APPROVED** [review]
